networks: 
  dev:
services:
#Base de donn√©es
  db:
    image: mysql:8.0
    container_name: db-mediatheque
    networks:
      - dev
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mediathequeroot
      MYSQL_DATABASE: mediatheque
#Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma-mediatheque
    restart: always
    depends_on:
      - db
    ports:
      - "8812:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mediathequeroot
    networks:
      - dev
#PHP (Serveur web)
  www:
    user: you
    build: ./docker/php
    container_name: php-mediatheque
    networks:
      - dev
    volumes:
      - ./site:/home/you/site
    ports:
      - 8811:8800
    environment:
      SHELL_VERBOSITY: DEBUG
#Mkdocs (Documentation)     
  mkdocs:
    container_name: doc-mediatheque
    build: ./docker/mkdocs
    ports:
      - "8813:8000"
    volumes:
      - ./mkdocs:/app
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - dev